apiVersion: v1
kind: Service
metadata:
  name: {{ include "gratis.fullname" . }}-api
  labels:
    {{- include "gratis.labels" . | nindent 4 }}
    {{- include "gratis.api.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "gratis.api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.grpc.port }}
      targetPort: grpc
      protocol: TCP
